apiVersion: v1
kind: Pod
metadata:
  name: demo-configmap-pod
spec:
  containers:
  - name: web-app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: app-config
